name: App CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable-ci.yml
    permissions:
      contents: read
      security-events: write
    with:
      node-version: '22'
      enable-checkov: false
